Option
jean-airoldie/humantime-serde pull request #6
Opened 2022-03-11 17:28 UTC by ijackson

As discussed in #5.  Thanks for your attention :-).

2022-03-11 18:06 UTC, jean-airoldie requested changes
Minor rewording to make it clear that its a helper module. Other than this minor thing, looks good to me.

2022-03-11 18:06 UTC, jean-airoldie commented on src/option.rs
> +//! Module to adaopt `humantime_serde` to `Option`
```suggestion
//! Convenience module to serialize `Option` via `humantime_serde`.
```

2022-03-11 18:30 UTC, ijackson commented on src/option.rs
> +//! Module to adaopt `humantime_serde` to `Option`
option: Clarify docs.

2022-03-11 18:30 UTC, ijackson commented
Cool. thanks.

2022-03-11 18:59 UTC, jean-airoldie approved these changes

2022-03-11 18:59 UTC, merged

2022-03-11 18:59 UTC, jean-airoldie commented
Alright, I'll make a release as well. Thanks!

2022-03-14 17:10 UTC, ijackson commented
Thanks :-).  Have switched our codebase to using the newly published version.